# Generated by Django 2.1.2 on 2018-10-24 22:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='credits',
            field=models.FloatField(default=4),
            preserve_default=False,
        ),
    ]
