# Generated by Django 3.0.3 on 2020-08-25 00:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0003_auto_20200824_1315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='major',
            old_name='courses',
            new_name='university_courses',
        ),
        migrations.RenameModel(
            old_name='Course',
            new_name='UniversityCourse',
        ),
        migrations.CreateModel(
            name='CommunityCollegeCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_number', models.CharField(max_length=10)),
                ('course_name', models.CharField(max_length=50)),
                ('credits', models.FloatField()),
                ('department', models.CharField(max_length=100)),
                ('pre_reqs', models.CharField(max_length=50)),
                ('course_description', models.TextField()),
                ('course_outcomes', models.TextField()),
                ('course_URL', models.URLField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.College')),
                ('course_equivalent', models.ManyToManyField(to='courses.UniversityCourse')),
            ],
            options={
                'ordering': ['course_number'],
            },
        ),
        migrations.AddField(
            model_name='major',
            name='community_college_courses',
            field=models.ManyToManyField(to='courses.CommunityCollegeCourse'),
        ),
    ]
