# Generated by Django 3.0.3 on 2020-08-25 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20200825_0805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='major',
            name='university_courses',
        ),
        migrations.AlterField(
            model_name='major',
            name='community_college_courses',
            field=models.ManyToManyField(blank=True, null=True, to='courses.CommunityCollegeCourse'),
        ),
    ]
