# Generated by Django 3.0.3 on 2020-08-25 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20200825_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='major',
            name='community_college_courses',
            field=models.ManyToManyField(to='courses.CommunityCollegeCourse'),
        ),
    ]
