site_name: Oregon-Transfer-App-Docs

# Configuration
theme:
  name: 'material'
  custom_dir: 'theme'
  language: 'en'
  palette:
    primary: 'green'
    accent: 'light green'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  logo:
    icon: 'build'

# Markdown Extensions
markdown_extensions:
  - admonition
  - footnotes
  - toc
repo_url: https://github.com/ProfessorKazarinoff/oregon-transfer-app
copyright: 'Copyright &copy; 2018 Peter D. Kazarinoff'
